---
# tasks file for arillso.fqdn

- block:
    - name: 'Windows : Change the hostname to {{ inventory_hostname_short }}'
      win_hostname:
        name: '{{ inventory_hostname_short }}'

  when: inventory_hostname_short | lower != ansible_hostname | lower
  tags:
    - configuration
